
module.exports = {
twitterFeeds: [{ date: 'Sat Oct 31 21:52:18 +0000 2015',
  source_type: 'twitter',
  location: 'Santo Domingo, RD.',
  text: 'RT @DaniloPaulinoR: Comisión Nacional de Energía asesta duro golpe al dengue - https://t.co/FWCNiG8vWC @cne_rd',
  language: 'es' },
{ date: 'Sat Oct 31 21:52:36 +0000 2015',
  source_type: 'twitter',
  location: 'Angola',
  text: '#FORÇA_SUPREMA \n\n°• Espalha tipo ebola•°\n\nPatrão da zOna ✌󾭻#Foii',
  language: 'pt' },
{ date: 'Sat Oct 31 21:52:40 +0000 2015',
  source_type: 'twitter',
  location: 'Mexico',
  text: 'Tienes dengue? — Si https://t.co/MsaQxk1Wmg',
  language: 'es' },
{ date: 'Sat Oct 31 21:52:40 +0000 2015',
  source_type: 'twitter',
  location: 'Mexico',
  text: 'I have dengue',
  language: 'en' },
{ date: 'Sat Oct 31 21:52:40 +0000 2015',
  source_type: 'twitter',
  location: 'Mexico',
  text: 'I love my boyfriend',
  language: 'en' },
{ date: 'Mon Nov 02 13:15:58 +0000 2015',
  source_type: 'twitter',
  location: 'nyköping',
  text: 'Hahahah vrf så skön och skämtar om ebola @LizetteLundh &lt;/3 https://t.co/Eg2UTPn5Kc',
  language: 'sv' },
{ date: 'Mon Nov 02 13:15:59 +0000 2015',
  source_type: 'twitter',
  location: 'Rochester, NY',
  text: 'I sont even ask ebola questions at work anymore',
  language: 'en' },
{ date: 'Mon Nov 02 13:16:01 +0000 2015',
  source_type: 'twitter',
  location: 'Toulouse, Midi-Pyrénées',
  text: 'RT @RTI_Officiel: Guinée- Un bébé né de "parents saints" a été déclaré positif au virus Ebola dans la préfecture de Forécariah. @rti_offici…',
  language: 'fr' },
{ date: 'Mon Nov 02 13:16:18 +0000 2015',
  source_type: 'twitter',
  location: 'Cameroun Douala',
  text: 'RT @afrikfoot: La FIFA et Eto’o engagés dans la lutte contre le virus Ebola https://t.co/rpyOGyteKJ',
  language: 'fr' },
{ date: 'Mon Nov 02 13:16:26 +0000 2015',
  source_type: 'twitter',
  location: 'lescout',
  text: 'RT @expertisefrance: #RetexEbola : les acteurs de la lutte contre Ebola réunis à Paris pour partager leurs expériences ! @AnnickGirardin ht…',
  language: 'fr' },
{ date: 'Mon Nov 02 13:16:38 +0000 2015',
  source_type: 'twitter',
  location: 'Skandinavien',
  text: 'Newsroom HIV | Malaria remains the number one cause of hospitalisation and death in Africa - Despite this decrease… https://t.co/IcuYpz6s6A',
  language: 'en' },
{ date: 'Mon Nov 02 13:16:39 +0000 2015',
  source_type: 'twitter',
  location: 'Oriente. Venezuela',
  text: '#LineaVitalSalud Incidencia del dengue ha aumentado 30 veces en los últimos 50 años https://t.co/TxAHmSyIzo',
  language: 'es' },
{ date: 'Mon Nov 02 13:16:41 +0000 2015',
  source_type: 'twitter',
  location: 'USA',
  text: 'Daily Deals &gt;&gt; https://t.co/Lrs6XpjwpD #0092 AVIAN-X AXF OUTFITTER FLOCKED CANADA GOOSE LESSER DECOY 12 PACK WITH … https://t.co/fMiBanxvAs',
  language: 'en' },
{ date: 'Mon Nov 02 13:17:00 +0000 2015',
  source_type: 'twitter',
  location: 'Evreux, FRANCE',
  text: 'RT @laFHF: En direct w/ @manuelvalls salue la mobilisation sans relâche des hospitaliers publics : #Ebola, grippe, #ambulatoire https://t.c…',
  language: 'fr' },
{ date: 'Mon Nov 02 13:17:38 +0000 2015',
  source_type: 'twitter',
  location: 'Alpes de Haute Provence',
  text: 'Immobilier : Hollande distribue du PTZ comme d’autres la malaria https://t.co/MlgxLIAtFI',
  language: 'fr' },
{ date: 'Mon Nov 02 13:17:42 +0000 2015',
  source_type: 'twitter',
  location: 'NC',
  text: 'I\'ll let you guys know if I have the Ebola.',
  language: 'en' },
{ date: 'Mon Nov 02 13:17:43 +0000 2015',
  source_type: 'twitter',
  location: 'Santo Domingo',
  text: 'Inapa se integra a la guerra contra el dengue con más de mil empleados https://t.co/HKSKLOaGRz https://t.co/4TV1V0fDSY',
  language: 'es' },
{ date: 'Mon Nov 02 13:17:57 +0000 2015',
  source_type: 'twitter',
  location: 'Rep Dominicana',
  text: 'Energía y Minas se suma a prevención de con suersonal y el liderazgo comunitario de Cotuí | https://t.co/ziaFfYTyao https://t.co/njVl0eeFIB',
  language: 'es' },
{ date: 'Mon Nov 02 13:18:20 +0000 2015',
  source_type: 'twitter',
  location: 'Bahía Blanca, Argentina',
  text: 'Que lindos bosteros avian ayer 👌😆😘💓❤',
  language: 'es' },

{ date: 'Wed Nov 04 15:17:00 +0000 2015',
  source_type: 'twitter',
  location: 'Oakland, California',
  text: 'Namibia HIV/AIDS #HiAP efforts have led to declines but hot spots remain- must prioritize specific populations+challenges #APHA15 #phiAPHA',
  language: 'en' },

{ date: 'Wed Nov 04 15:17:01 +0000 2015',
  source_type: 'twitter',
  location: 'Republica Dominicana',
  text: 'RT @DaniloJuventud: Concluye con éxito Operativo PREVENIR PARA VIVIR de la JuventudPLD. Informan de la incursión en 4 mil 250  hogares… htt…',
  language: 'es' },
{ date: 'Wed Nov 04 15:17:04 +0000 2015',
  source_type: 'twitter',
  location: 'Abuja, Nigeria',
  text: 'Measles Vaccination - Bauchi Targets 1.6 Million Children - https://t.co/NllToZumsN https://t.co/GESUhxEKts',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:05 +0000 2015',
  source_type: 'twitter',
  location: 'Thornbury',
  text: 'RT @COMOmeningitis: Hooray! #Meningitis B vaccine introduction into Gibraltar\'s childhood vaccination programme! https://t.co/EdPaTFcGUX',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:07 +0000 2015',
  source_type: 'twitter',
  location: 'Santo Domingo',
  text: 'El Ánalisis sobre el dengue en RD en la Mesa de Esta Noche Mariasela #Video: Parte 1 Parte 2 Uploading…\nThe po... https://t.co/E2ZASu3uS2',
  language: 'es' },
{ date: 'Wed Nov 04 15:17:08 +0000 2015',
  source_type: 'twitter',
  location: 'Bogotá, Colombia',
  text: 'RT @AlbertoBernalLe: El paraíso socialista....el socialismo es la ideología del fracasado, del resentido, del inseguro, del perezoso. \n   h…',
  language: 'es' },
{ date: 'Wed Nov 04 15:17:15 +0000 2015',
  source_type: 'twitter',
  location: 'New York',
  text: 'Strep throat and 104 fever Fml 😨😨😨',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:17 +0000 2015',
  source_type: 'twitter',
  location: 'Saint Paul, Minnesota',
  text: 'RT @BillGates: A drug used widely to treat tropical diseases may also help stop malaria from spreading: https://t.co/icdZeeOVbT https://t.c…',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:17 +0000 2015',
  source_type: 'twitter',
  location: 'Lahore',
  text: 'RT @mahobili: not sure if Lahore has fog, dust, dengue spray or surprise visit of pollution from India :p',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:32 +0000 2015',
  source_type: 'twitter',
  location: 'Nigeria',
  text: 'RT @nigerianblogger: Nigerian Ebola survivor gives birth in US hospital\n\nhttps://t.co/mFqqirI1Ve',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:36 +0000 2015',
  source_type: 'twitter',
  location: 'Brighton & Hove, UK',
  text: 'RT @guardian: With Ebola finally in retreat, Sierra Leoneans are yearning for a return to normality https://t.co/3kRKKTS8zW https://t.co/is…',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:45 +0000 2015',
  source_type: 'twitter',
  location: 'Nigeria',
  text: 'Ebola Survivor, Ada Igonoh Welcomes Baby Girl https://t.co/sqj6f5q2s1 via https://t.co/wYzTr61dZM',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:52 +0000 2015',
  source_type: 'twitter',
  location: 'Miskatonic University, Arkham',
  text: 'I think I just saw a monster ebola virus on the stairs. https://t.co/WhXpX3Dq9q',
  language: 'en' },
{ date: 'Wed Nov 04 15:17:59 +0000 2015',
  source_type: 'twitter',
  location: 'Valenciennes',
  text: 'RT AFPMarseille: A Nîmes, une étude de santé publique après sept cas de dengue survenus cet été #AFP https://t.co/dl2mWKlHSd #infloodwetru…',
  language: 'fr' },
{ date: 'Wed Nov 04 15:18:05 +0000 2015',
  source_type: 'twitter',
  location: 'Caracas, Distrito Capital',
  text: 'Hoy mi mirada de odio está tan en su punto que veo fijo a alguien y mínimo le contagio ebola.',
  language: 'es' },
{ date: 'Wed Nov 04 15:18:06 +0000 2015',
  source_type: 'twitter',
  location: 'España',
  text: 'Según la OMS, la mortalidad de la tuberculosis se ha reducido a la mitad desde 1990. https://t.co/fJdbuzF5Ku https://t.co/z4LrfhYuOp',
  language: 'es' },
{ date: 'Wed Nov 04 15:18:06 +0000 2015',
  source_type: 'twitter',
  location: 'Abuja, Nigeria',
  text: 'RT @nighealthwatch: Want to know more about #Polio immunization boycott in Northern Nigeria? Visit https://t.co/aIwinc4E8M #NHWResources',
  language: 'en' },
{ date: 'Wed Nov 04 15:18:12 +0000 2015',
  source_type: 'twitter',
  location: 'Lahore, Pakistan',
  text: 'RT @mahobili: not sure if Lahore has fog, dust, dengue spray or surprise visit of pollution from India :p',
  language: 'en' },
{ date: 'Wed Nov 04 15:18:12 +0000 2015',
  source_type: 'twitter',
  location: 'La Altagracia, Dominican Republic',
  text: '@JoelBelandray no me ayudas JOEL😒 pd: no e\' dengue',
  language: 'es' },
{ date: 'Wed Nov 04 15:18:13 +0000 2015',
  source_type: 'twitter',
  location: 'Living in Manhiça, Mozambique',
  text: 'RT @JoanPauMillet: XIX Taller Internacional de #Tuberculosis en #Barcelona. Inscripciones abiertas. @JoanCayla https://t.co/2I0aUaYEoo http…',
  language: 'es' },
{ date: 'Wed Nov 04 15:18:14 +0000 2015',
  source_type: 'twitter',
  location: 'Washington, DC',
  text: 'RT @FifiLawless: @hichrisfabian "I don\'t want an Ebola system, I want a 911 system that works". Disease and the Info highway. #FungForum #U…',
  language: 'en' },
{ date: 'Wed Nov 04 15:18:20 +0000 2015',
  source_type: 'twitter',
  location: 'Colima',
  text: 'Thank you vaccines: Polio may be eradicated from the face of the Earth by 2018\nhttps://t.co/7RN3Wnh101 vía @BadAstronomer',
  language: 'en' },
{ date: 'Wed Nov 04 15:18:25 +0000 2015',
  source_type: 'twitter',
  location: 'Venezuela',
  text: 'Así combaten el dengue y la chikungunya en Chacao https://t.co/vEkCTzlAHV',
  language: 'es' },
{ date: 'Wed Nov 04 15:18:28 +0000 2015',
  source_type: 'twitter',
  location: 'SAN DIEGO',
  text: 'RT @NMAtweets: Vaccines are now available to protect against all five major strains of #meningitis in the US. https://t.co/Z6l2ATUA8F',
  language: 'en' },
{ date: 'Wed Nov 04 15:18:29 +0000 2015',
  source_type: 'twitter',
  location: 'México',
  text: 'Mi profesor de física es un mirrey con polio.',
  language: 'es' },
{ date: 'Wed Nov 04 15:18:44 +0000 2015',
  source_type: 'twitter',
  location: 'Abuja, Nigeria',
  text: 'RT @DrAAjayi: The first few weeks of a baby\'s life are the most dangerous - #pneumonia kills almost 1M children each year https://t.co/teqc…',
  language: 'en' },
{ date: 'Wed Nov 04 15:18:50 +0000 2015',
  source_type: 'twitter',
  location: 'South Africa',
  text: 'SA to manufacture local pneumonia vaccine by 2020 – WHO said in 2005 1.6mil people die of disease annually https://t.co/pWBA0rnXe3',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:00 +0000 2015',
  source_type: 'twitter',
  location: 'France',
  text: 'Ebola toujours là mais de bonnes nouvelles : épidémie éradiquée au Liberia. https://t.co/NACK3KXmkq @MSF_france',
  language: 'fr' },
{ date: 'Wed Nov 04 15:19:00 +0000 2015',
  source_type: 'twitter',
  location: 'Nigeria',
  text: '#NIHGSK #EbolaVaccine #Update  https://t.co/A3xICLFXrI',
  language: 'und' },
{ date: 'Wed Nov 04 15:19:02 +0000 2015',
  source_type: 'twitter',
  location: 'Pasig City, Manila PH',
  text: 'RT @BillGates: A drug used widely to treat tropical diseases may also help stop malaria from spreading: https://t.co/icdZeeOVbT https://t.c…',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:07 +0000 2015',
  source_type: 'twitter',
  location: 'Canaman',
  text: '@yxesjap dengue na garo yanhaha',
  language: 'pt' },
{ date: 'Wed Nov 04 15:19:08 +0000 2015',
  source_type: 'twitter',
  location: 'México',
  text: 'RT @SSalud_mx: #SabíasQue La #hepatitis a veces es asintomática. https://t.co/0EKgDARwKr',
  language: 'es' },
{ date: 'Wed Nov 04 15:19:11 +0000 2015',
  source_type: 'twitter',
  location: 'Fairport New York',
  text: '@mystery_butt I had pneumonia in 10th grade, and bronchitis last year, and I\'m starting to wonder if I have it again :S',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:17 +0000 2015',
  source_type: 'twitter',
  location: 'USA',
  text: 'The world is running short of yellow fever vaccines—and millions are at risk https://t.co/lK7rHedEHP',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:18 +0000 2015',
  source_type: 'twitter',
  location: 'Caracas',
  text: '"Siguen muriendo internos por falta de asistencia médica, mueren de vih/sida, tuberculosis. Existe mucha sarna" HP https://t.co/IoWoJZmbKL',
  language: 'es' },
{ date: 'Wed Nov 04 15:19:20 +0000 2015',
  source_type: 'twitter',
  location: 'Maldives',
  text: 'RT @MSF: Our latest #Ebola crisis update: overview &amp; highlights per country #Guinea #Liberia #SierraLeone https://t.co/yxf3fCGv8P',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:21 +0000 2015',
  source_type: 'twitter',
  location: 'NYC',
  text: 'RT @guardian: As Sierra Leone counts the days to Ebola all clear, safe burial teams press on | Nadene Ghouri https://t.co/Gzww9lbKXF',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:21 +0000 2015',
  source_type: 'twitter',
  location: 'USA',
  text: 'RT @jonlieffmd: The Ebola virus may persist in men\'s semen for 9 months after they were initially infected and be transmitted https://t.co/…',
  language: 'en' },

{ date: 'Wed Nov 04 15:19:25 +0000 2015',
  source_type: 'twitter',
  location: 'Malaysia',
  text: '@HishammuddinH2O Sir, I heard that your besan admitted to hospital due to dengue. I wish him a speedy recover.',
  language: 'en' },

{ date: 'Wed Nov 04 15:19:29 +0000 2015',
  source_type: 'twitter',
  location: 'São Paulo',
  text: 'Vai ter dengue lá no RJ, Michel Bastos',
  language: 'pt' },
{ date: 'Wed Nov 04 15:19:30 +0000 2015',
  source_type: 'twitter',
  location: 'Atlanta, GA',
  text: 'RT @BillGates: A drug used widely to treat tropical diseases may also help stop malaria from spreading: https://t.co/icdZeeOVbT https://t.c…',
  language: 'en' },

{ date: 'Wed Nov 04 15:19:32 +0000 2015',
  source_type: 'twitter',
  location: 'USA',
  text: 'RT @GoogleFacts: One of the best ways to convince people of the benefits of vaccinations is to show them pictures of a child with measles, …',
  language: 'en' },

{ date: 'Wed Nov 04 15:19:36 +0000 2015',
  source_type: 'twitter',
  location: 'Lagos, Nigeria',
  text: 'Malaria well played👏',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:46 +0000 2015',
  source_type: 'twitter',
  location: 'Ankara',
  text: 'RT @NatGeoEsp: Según la OMS, la mortalidad de la tuberculosis se ha reducido a la mitad desde 1990. https://t.co/fJdbuzF5Ku https://t.co/z4…',
  language: 'es' },
{ date: 'Wed Nov 04 15:19:49 +0000 2015',
  source_type: 'twitter',
  location: 'San Salvador, El Salvador',
  text: 'RT @VctorEmilioPino: VIDEO FUMIGACIÓN CONTRA EL DENGUE REALIZADA DIRECTIVA DEPTAL SAN SALVADOR @PCN_Oficial @PrensaPCN https://t.co/CNRsPUd…',
  language: 'es' },
{ date: 'Wed Nov 04 15:19:52 +0000 2015',
  source_type: 'twitter',
  location: 'SAN DIEGO',
  text: 'RT @NFIDvaccines: #GetVaccinated against #measles. Learn more: https://t.co/8zhSpoCyze https://t.co/Wkfl7Ooc9n',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:54 +0000 2015',
  source_type: 'twitter',
  location: ' Philippines',
  text: 'Tatlo na silang nasa ospital jusko😭😭😭 dalawang dengue boy 😞',
  language: 'tl' },
{ date: 'Wed Nov 04 15:19:56 +0000 2015',
  source_type: 'twitter',
  location: 'Mumbai',
  text: 'RT @guardian: With Ebola finally in retreat, Sierra Leoneans are yearning for a return to normality https://t.co/3kRKKTS8zW https://t.co/is…',
  language: 'en' },
{ date: 'Wed Nov 04 15:19:59 +0000 2015',
  source_type: 'twitter',
  location: 'California',
  text: 'RT @BillGates: A drug used widely to treat tropical diseases may also help stop malaria from spreading: https://t.co/icdZeeOVbT https://t.c…',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:04 +0000 2015',
  source_type: 'twitter',
  location: 'Padova',
  text: 'The #lipid moiety of #brincidofovir is required for in vitro #antiviral #activity against #Ebola #... https://t.co/VIyPeFC3NK',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:04 +0000 2015',
  source_type: 'twitter',
  location: 'República Dominicana',
  text: 'Reportan baja de casos de dengue en el Robert Reid - https://t.co/hI3dF0zbsH https://t.co/mdG3wlVdpe',
  language: 'es' },
{ date: 'Wed Nov 04 15:20:09 +0000 2015',
  source_type: 'twitter',
  location: 'Padova',
  text: 'The #lipid moiety of #brincidofovir is required for in vitro #antiviral #activity against #Ebola #virus... https://t.co/qJXIQXk1Hn',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:15 +0000 2015',
  source_type: 'twitter',
  location: 'Wichita, Kansas',
  text: 'RT @SaludHEALTHinfo: RT @NFIDvaccines: #GetVaccinated against #measles. Learn more: https://t.co/8zhSpoCyze https://t.co/Wkfl7Ooc9n',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:15 +0000 2015',
  source_type: 'twitter',
  location: 'Weehawken, NJ',
  text: 'RT @GoogleFacts: One of the best ways to convince people of the benefits of vaccinations is to show them pictures of a child with measles, …',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:17 +0000 2015',
  source_type: 'twitter',
  location: 'República Dominicana',
  text: 'Algo Nuevo: El Ánalisis sobre el dengue en RD en la Mesa de Esta Noche Mariasela… https://t.co/qQOGwAIN31 #cachicha https://t.co/fTMjZCQMM4',
  language: 'es' },
{ date: 'Wed Nov 04 15:20:22 +0000 2015',
  source_type: 'twitter',
  location: 'DELHI',
  text: 'RT @GoogleFacts: One of the best ways to convince people of the benefits of vaccinations is to show them pictures of a child with measles, …',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:24 +0000 2015',
  source_type: 'twitter',
  location: 'Venezuela',
  text: '#InformeOVP Siguen muriendo reos por enfermedades como Vih, tuberculosis, etc En 2015 se desató la sarna y enfermedades dermatológicas',
  language: 'es' },
{ date: 'Wed Nov 04 15:20:26 +0000 2015',
  source_type: 'twitter',
  location: 'Alabama',
  text: '@kittykaresless but we live in America. Ebola has affected me zero. Polio and flu in the 20s America was a legit threat of life',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:28 +0000 2015',
  source_type: 'twitter',
  location: 'Atlanta, USA',
  text: 'RT @Davos: Why medicine alone is not enough to stop tuberculosis https://t.co/AIyXA8I0NK https://t.co/GNiy5fZ8AZ',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:28 +0000 2015',
  source_type: 'twitter',
  location: 'Bulgaria',
  text: 'Не помага! Сума ти и пъти пробвах така! Не хващат! https://t.co/GBBPIIHddW',
  language: 'bg' },
{ date: 'Wed Nov 04 15:20:29 +0000 2015',
  source_type: 'twitter',
  location: 'Long Lake NY',
  text: 'RT @Rose_concern: As Sierra Leone counts the days to Ebola all clear, safe burial teams press on @concern  | Nadene Ghouri https://t.co/K4C…',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:33 +0000 2015',
  source_type: 'twitter',
  location: 'Swarthmore, PA',
  text: 'RT @GoogleFacts: One of the best ways to convince people of the benefits of vaccinations is to show them pictures of a child with measles, …',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:34 +0000 2015',
  source_type: 'twitter',
  location: 'Lagos',
  text: 'WELCOME TO SHOUTGIST: Photo: Nigerian Doctor, Ebola Survivor Ada Igonoh ... https://t.co/NwTBmY5Hie',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:37 +0000 2015',
  source_type: 'twitter',
  location: 'NYC',
  text: 'RT @DrJayVarma: TB causes as many deaths as HIV/AIDS globally, yet global TB budget ($5B) just 1/4 of global HIV budget ($19B).  https://t.…',
  language: 'en' },
{ date: 'Wed Nov 04 15:20:42 +0000 2015',
  source_type: 'twitter',
  location: 'México',
  text: 'En ocasiones la infección por fiebre #Chikungunya pasa inadvertida o se confunde con #dengue https://t.co/RPXsY1LgPv',
  language: 'es' },
{ date: 'Wed Nov 04 15:20:44 +0000 2015',
  source_type: 'twitter',
  location: 'San Julián, Jalisco',
  text: 'RT @SecEducacionJal: Para evitar la influenza te recomendamos seguir estas medidas https://t.co/A2DpCxq6Br',
  language: 'es' },
{ date: 'Wed Nov 04 15:20:45 +0000 2015',
  source_type: 'twitter',
  location: 'Venezuela',
  text: 'RT @EfectoCocuyo: #InformeOVP Siguen muriendo reos por enfermedades como Vih, tuberculosis, etc En 2015 se desató la sarna y enfermedades d…',
  language: 'es' },
{ date: 'Wed Nov 04 15:20:52 +0000 2015',
  source_type: 'twitter',
  location: 'MERIDA',
  text: 'RT @vertvnoticias: Así combaten el dengue y la chikungunya en Chacao https://t.co/vEkCTzlAHV',
  language: 'es' },
{ date: 'Wed Nov 04 15:21:03 +0000 2015',
  source_type: 'twitter',
  location: 'Mexico',
  text: 'RT @SSalud_mx: En ocasiones la infección por fiebre #Chikungunya pasa inadvertida o se confunde con #dengue https://t.co/RPXsY1LgPv',
  language: 'es' },
{ date: 'Wed Nov 04 15:21:25 +0000 2015',
  source_type: 'twitter',
  location: 'Brookings, SD',
  text: 'If every time you have a neck pain you think you might have bacterial meningitis, you might be a pharm kid.',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:27 +0000 2015',
  source_type: 'twitter',
  location: 'Boca Raton, Florida',
  text: 'RT @bnwomeh: Congrats @AdaIgonoh #Ebola survivor who just gave birth to baby girl! https://t.co/vp0Kt3eySN https://t.co/LYTzsUAWFI',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:29 +0000 2015',
  source_type: 'twitter',
  location: 'Karachi',
  text: 'RT @GoogleFacts: One of the best ways to convince people of the benefits of vaccinations is to show them pictures of a child with measles, …',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:34 +0000 2015',
  source_type: 'twitter',
  location: 'Chennai, Tamil Nadu',
  text: 'RT @imKBRshanthnu: Do Spread the word 😊 https://t.co/ci0ccLzf7l',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:36 +0000 2015',
  source_type: 'twitter',
  location: 'Dublin',
  text: 'RT @Rose_concern: As Sierra Leone counts the days to Ebola all clear, safe burial teams press on @concern  | Nadene Ghouri https://t.co/K4C…',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:36 +0000 2015',
  source_type: 'twitter',
  location: 'Atlanta',
  text: 'Guided simulation of Ebola response teams with @CDC officers #WAlearns #STEM https://t.co/zBZBAnUEwT',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:38 +0000 2015',
  source_type: 'twitter',
  location: 'Nigeria',
  text: 'Nigerian Ebola survivor gives birth in US hospital \nhttps://t.co/mFqqirI1Ve',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:46 +0000 2015',
  source_type: 'twitter',
  location: 'Chancay, Peru',
  text: 'Los depósitos de agua son criaderos de dengue y la chikungunya \n[Especial Web]→ https://t.co/fZ92d4VOoi https://t.co/s8MgMibuXk',
  language: 'es' },
{ date: 'Wed Nov 04 15:21:47 +0000 2015',
  source_type: 'twitter',
  location: 'Philippines',
  text: 'RT @GoogleFacts: One of the best ways to convince people of the benefits of vaccinations is to show them pictures of a child with measles, …',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:51 +0000 2015',
  source_type: 'twitter',
  location: 'Knoxville, TN',
  text: 'I was chased by a group of cholera infected people. Man they move fast.It’s like Rick in Walking Dead.  #utkcholeraexercise',
  language: 'en' },
{ date: 'Wed Nov 04 15:21:56 +0000 2015',
  source_type: 'twitter',
  location: 'pinamar, argentina',
  text: 'Estos días estuve tan enferma que no sé, seguro me agarró el ebola',
  language: 'es' },
{ date: 'Wed Nov 04 15:22:00 +0000 2015',
  source_type: 'twitter',
  location: 'Uganda',
  text: 'We helped to #distribute over 21 million #bed #nets across #Uganda https://t.co/xySPudHj66 #defeatmalaria  https://t.co/mLMI1beRVa',
  language: 'en' },
{ date: 'Wed Nov 04 15:22:02 +0000 2015',
  source_type: 'twitter',
  location: 'paris',
  text: 'RT @AFPMarseille: A Nîmes, une étude de santé publique après sept cas de dengue survenus cet été #AFP https://t.co/Q2kuJQWTDu',
  language: 'fr' },
{ date: 'Wed Nov 04 15:22:05 +0000 2015',
  source_type: 'twitter',
  location: 'Delhi, India',
  text: 'RT @mahobili: not sure if Lahore has fog, dust, dengue spray or surprise visit of pollution from India :p',
  language: 'en' },
{ date: 'Wed Nov 04 15:22:07 +0000 2015',
  source_type: 'twitter',
  location: 'Baltimore, MD',
  text: 'Two possible cases of dengue fever on the Big Island https://t.co/NfrqvjQD4C',
  language: 'en' },
{ date: 'Wed Nov 04 15:22:11 +0000 2015',
  source_type: 'twitter',
  location: 'Florida',
  text: 'Provide Funding for Mosquito Nets to Prevent Spread of Malaria https://t.co/8l9XqjrroZ via @ForceChange',
  language: 'en' },
{ date: 'Wed Nov 04 15:22:16 +0000 2015',
  source_type: 'twitter',
  location: 'Minneapolis, MN',
  text: 'RT @deedragonhunter: Looks for rusty knife, \napplies Ebola virus. \n\nLogs back into Facebook,\nto see who has it coming.',
  language: 'en' },
{ date: 'Wed Nov 04 15:22:16 +0000 2015',
  source_type: 'twitter',
  location: 'Monopoli Puglia ',
  text: 'RT @GCappellazz: @spinozait @pirata_21 Va bene possiamo trasformarlo in asilo e mandare Bertone in Africa a curare Ebola!',
  language: 'it' },
{ date: 'Wed Nov 04 15:22:17 +0000 2015',
  source_type: 'twitter',
  location: 'Kumasi, Ghana',
  text: 'RT @FifiLawless: @hichrisfabian "I don\'t want an Ebola system, I want a 911 system that works". Disease and the Info highway. #FungForum #U…',
  language: 'en' },
{ date: 'Wed Nov 04 15:22:18 +0000 2015',
  source_type: 'twitter',
  location: 'Volvera, Piemonte',
  text: 'RT @nigrizia: #Sudan: Epidemia di febbre emorragica dengue in #Darfur. #Africa https://t.co/fmdD5sdZk8 https://t.co/T7EzT9BPpi',
  language: 'it' }
  ]};